#pragma once

#include <sdkconfig.h>

#ifdef CONFIG_ENABLE_ICD_SERVER
#define CHIP_CONFIG_ENABLE_ICD_SERVER 1
#else
#define CHIP_CONFIG_ENABLE_ICD_SERVER 0
#endif

#ifdef CONFIG_ENABLE_ICD_LIT
#define CHIP_CONFIG_ENABLE_ICD_LIT 1
#else
#define CHIP_CONFIG_ENABLE_ICD_LIT 0
#endif

#ifdef CONFIG_ENABLE_ICD_CIP
#define CHIP_CONFIG_ENABLE_ICD_CIP 1
#else
#define CHIP_CONFIG_ENABLE_ICD_CIP 0
#endif

#ifdef CONFIG_ENABLE_ICD_USER_ACTIVE_MODE_TRIGGER
#define CHIP_CONFIG_ENABLE_ICD_UAT 1
#else
#define CHIP_CONFIG_ENABLE_ICD_UAT 0
#endif

#ifdef CONFIG_ICD_REPORT_ON_ACTIVE_MODE
#define ICD_REPORT_ON_ENTER_ACTIVE_MODE 1
#else
#define ICD_REPORT_ON_ENTER_ACTIVE_MODE 0
#endif

#ifdef CONFIG_ICD_MAX_NOTIFICATION_SUBSCRIBERS
#define ICD_MAX_NOTIFICATION_SUBSCRIBERS CONFIG_ICD_MAX_NOTIFICATION_SUBSCRIBERS
#else
#define ICD_MAX_NOTIFICATION_SUBSCRIBERS 1
#endif

#ifdef CONFIG_ICD_ENFORCE_SIT_SLOW_POLL_LIMIT
#define ICD_ENFORCE_SIT_SLOW_POLL_LIMIT 1
#else
#define ICD_ENFORCE_SIT_SLOW_POLL_LIMIT 0
#endif
